[package]
name = "expected_variable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
edit_distance = { path = "../edit_distance", version = "0.1.0" }
convert_case = "0.6.0"
